### PR TITLE
Draft of ZenIP 42204 for the deprecation of the mainchain shielded pool

### PR DESCRIPTION
**Pull request by doigensan**

### CODE REVIEW

**Comment by tarrenj** [comment]
Removing shielded transactions as a whole (instead of spending the effort to update them) is contradictory to the original goals of the project, IMHO.

**Comment by finpunk** [comment]
> Removing shielded transactions as a whole (instead of spending the effort to update them) is contradictory to the original goals of the project, IMHO.

It is contrary to the original goals of the project, which is why this is such an important discussion for the community to have.  This ZenIP is a response to growing community sentiment that is nervous about the shifting regulatory environment that could kill the project. Does the community want to stick to the original goal of transaction and coin privacy or has the trajectory of the project shifted to the point where it no longer makes sense. This is the big question. 

That said, this specific ZenIP is strictly related to deprecating the original shielded pool on the grounds that it is outdated technology and has increasing regulatory risk. What's not stated explicitly is that few people use the shielded pool and we have < 0.004 (0.4%) of the ZEN supply making use of the feature.

We have several options:

1. Do nothing.
2. Pivot away from coin privacy in the Mainchain.
3. Modernize the shielding circuit. 
4. Remove coin privacy from the Mainchain and have a privacy sidechain.

**Comment by Daily-Hong** [comment]
With the removal of unnecessary regulations that have always stood in our way, our biggest weakness will be eliminated, allowing us to compete properly in a larger market.

**Comment by axpnet** [comment]
ZK is where everyone wants to go right now, I hope you're not just about to remove the most requested feature of these times and times to come.

Everyone is talking about ZK and Horizen is not pushing this new trend at all although he could teach others what ZK means. It would be paradoxical right now to remove this feature. Maybe wait a couple of years ... but right now it's better to ride the trend ;-)

**Comment by kgfoundrydig** [comment]
> 1. Do nothing.

That's the answer, plain and simple.  Sprout isn't a threat that legislators or law enforcers take seriously.  It's not popular enough to bother with.  Save your time and energy.

**Comment by UnidentifiedSaturnMan** [comment]
Many people are under the illusion that zk is completely gone from ZEN. What's clear is that $ZEN is a platform. It has to be used extensively. In that sense, I hope that the fact that zk still exists in the side chain is well conveyed to people.

**Review by zain-cheng — APPROVED** [review]

**Review by rosariopabst — APPROVED** [review]
Approved based on vast community support to remove the shielded pool from the mainchain

**Pull request merged**
